#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void tasksync__produceflow_spg 
    (tasksync__alpha_type* data_source);

void tasksync__computerflow_spg 
    (tasksync__alpha_type* data_source,
    tasksync__alpha_type data_sink);

void tasksync__consumeflow_spg 
    (tasksync__alpha_type data_sink);

#endif
