#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_singletask_spg (void);
void tasksync__singletask_spg (void)
{

  user_singletask_spg ();
}


