#include <deployment.h>
#include <po_hi_types.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_entity_t __po_hi_port_global_to_entity[__PO_HI_NB_PORTS] = {pr_a_producer_k_entity,pr_a_computer_k_entity,pr_a_computer_k_entity,pr_a_consumer_k_entity};
char* __po_hi_port_global_names[__PO_HI_NB_PORTS] = {"producer_global_data_source","computer_global_data_sink","computer_global_data_source","consumer_global_data_sink"};
char* __po_hi_port_global_model_names[__PO_HI_NB_PORTS] = {"data_source","data_sink","data_source","data_sink"};
__po_hi_port_kind_t __po_hi_port_global_kind[__PO_HI_NB_PORTS] = {__PO_HI_OUT_EVENT_DATA_INTRA_PROCESS,__PO_HI_IN_EVENT_DATA_INTRA_PROCESS,__PO_HI_OUT_EVENT_DATA_INTRA_PROCESS,__PO_HI_IN_EVENT_DATA_INTRA_PROCESS};
__po_hi_uint32_t __po_hi_port_global_data_size[__PO_HI_NB_PORTS] = {sizeof (int),sizeof (int),sizeof (int),sizeof (int)};
__po_hi_uint32_t __po_hi_port_global_queue_size[__PO_HI_NB_PORTS] = {1,1,1,1};
__po_hi_local_port_t __po_hi_port_global_to_local[__PO_HI_NB_PORTS] = {producer_local_data_source,computer_local_data_sink,computer_local_data_source,consumer_local_data_sink};
__po_hi_node_t __po_hi_entity_table[__PO_HI_NB_ENTITIES] = {pr_a_k,pr_a_k,pr_a_k};
__po_hi_uint8_t __po_hi_deployment_endiannesses[__PO_HI_NB_NODES] = {__PO_HI_LITTLEENDIAN};
__po_hi_device_id __po_hi_port_to_device[__PO_HI_NB_PORTS] = {0,0,0,0};

