--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Activity;
with PolyORB_HI.Messages;
with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Marshallers is

  --  Marshallers for interface type of thread receiver.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.radar_system_receiver_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.radar_system_receiver_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.radar_system_receiver_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type target_distance

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Target_Distance;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Target_Distance;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread analyser.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.radar_system_analyser_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.radar_system_analyser_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.radar_system_analyser_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type target_position.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Target_Position_impl;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Target_Position_impl;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type motor_position

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.Motor_Position;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.Motor_Position;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread display_panel.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.radar_system_display_panel_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.radar_system_display_panel_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.radar_system_display_panel_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread transmitter.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.radar_system_transmitter_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.radar_system_transmitter_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.radar_system_transmitter_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread controller.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.radar_system_controller_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.radar_system_controller_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.radar_system_controller_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

end PolyORB_HI_Generated.Marshallers;
