--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type Target_Distance is
   new Standard.Integer;

  --  target_distance'Object_Size ~= 32 bits

  Target_Distance_Default_Value : constant Target_Distance :=
   0;

  type Motor_Position is
   new Standard.Integer;

  --  motor_position'Object_Size ~= 32 bits

  Motor_Position_Default_Value : constant Motor_Position :=
   0;

  type Target_Position_impl is
    record
      theta : PolyORB_HI_Generated.Types.Motor_Position;
      rho : PolyORB_HI_Generated.Types.Target_Distance;
    end record;

  --  target_position_impl'Object_Size ~= 64 bits

  for Target_Position_impl'Alignment use 8;

  Target_Position_impl_Default_Value : constant Target_Position_impl :=
   (theta => 0,
    rho => 0);

end PolyORB_HI_Generated.Types;
